name: chk1

on:
  schedule:
  - cron: "30 16 * * *"
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Pip Cache
        id: pip_cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}
          restore-keys: pip-

      - name: Install requirements
        if: steps.pip_cache.outputs.cache-hit != 'true'
        run: pip3 install -r requirements.txt

      - name: Run chk
        run: python3 main.py --cookie_string "${{ secrets.GLADOS_COOKIE }}"
        env: 
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          SERVERCHAN_SENDKEY: ${{ secrets.SERVERCHAN_SENDKEY }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          BARK_DEVICEKEY: ${{ secrets.BARK_DEVICEKEY }}